# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - ./config.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  webserver:
    build: .
    volumes:
       - ./config.py:/usr/src/app/config.py
    ports:
      - 8000:8000
    env_file:
      - ./config.env
